# Generated by Django 4.1.4 on 2022-12-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='password',
        ),
    ]
