# Generated by Django 4.1.4 on 2022-12-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_usersignup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usersignup',
            name='password',
            field=models.CharField(default='BLAHH', max_length=150),
        ),
    ]
