# Generated by Django 4.1.4 on 2022-12-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_usersignup_groups_usersignup_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
